version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip ci] build(deps):"
      prefix-development: "[skip ci] build(deps-dev):"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[skip ci] build(deps):"
    open-pull-requests-limit: 5
